### ISSUE TITLE
Can't interact with text boxes after a pop up.

### ISSUE THREAD

**Issue by footbananas** [eriqjaffe/OOTP-Uniform-Maker#60]
After there's a pop up from the app, like a notification of a new update or when trying to load a uniform, I'm unable to interact with the text boxes. I can click them, but am unable to type in them. Love the program by the way!!

**Comment by eriqjaffe** [comment]
Well, I can replicate that but I'll be darned if can figure out why since they're just standard text inputs.  FWIW opening the developer console (Ctrl-Shift-I) and closing it again seems to make them editable again, although I couldn't explain why.

I'll take a look at it and see if I can figure out what's going on though.
